// Generated by CoffeeScript 1.8.0
var RedWire, expect, http;

expect = require('chai').expect;

RedWire = require('../');

http = require('http');

describe('CORS', function() {
  var testServer;
  testServer = function(port, cb) {
    var server;
    server = http.createServer(function(req, res) {
      res.write('');
      res.end();
      cb(req);
      return server.close();
    });
    return server.listen(port);
  };
  it('should not be present when no servers are provided', function(done) {
    var options, passed, redwire;
    redwire = new RedWire({
      http: {
        port: 53437
      }
    });
    redwire.http('http://localhost:53437').use(redwire.cors([])).use(redwire.proxy('http://localhost:54677'));
    passed = false;
    testServer(54677, function(req) {
      return passed = true;
    });
    options = {
      hostname: 'localhost',
      port: 53437,
      headers: {
        referer: 'http://example.com'
      }
    };
    return http.get(options, function(res) {
      expect(res.headers['access-control-allow-origin']).to.be.undefined();
      expect(passed).to.be["true"]();
      redwire.close();
      return done();
    });
  });
  return it('should match the referer and return a single domain', function(done) {
    var options, passed, redwire;
    redwire = new RedWire({
      http: {
        port: 53438
      }
    });
    redwire.http('http://localhost:53438').use(redwire.cors(['http://default.com', 'http://example.com', 'http://test.com'])).use(redwire.proxy('http://localhost:54678'));
    passed = false;
    testServer(54678, function(req) {
      return passed = true;
    });
    options = {
      hostname: 'localhost',
      port: 53438,
      headers: {
        referer: 'http://example.com'
      }
    };
    return http.get(options, function(res) {
      expect(res.headers['access-control-allow-origin']).to.be.eql('http://example.com');
      expect(passed).to.be["true"]();
      redwire.close();
      return done();
    });
  });
});
