// Generated by CoffeeScript 1.9.2
var RedWire, expect, http;

expect = require('chai').expect;

RedWire = require('../src/redwire');

http = require('http');

describe('RedWire wildcard', function() {
  var testHttpServer;
  testHttpServer = function(port, cb) {
    var server;
    server = http.createServer(function(req, res) {
      res.write('');
      res.end();
      cb(req);
      return server.close();
    });
    return server.listen(port);
  };
  return it('should allow wildcards', function(done) {
    var redwire, sawit;
    redwire = new RedWire({
      http: {
        port: 63436
      }
    });
    redwire.http('*', 'localhost:64676');
    sawit = false;
    testHttpServer(64676, function(req) {
      return sawit = true;
    });
    return http.get('http://localhost:63436', function(res) {
      redwire.close();
      expect(sawit).to.be["true"]();
      return done();
    });
  });
});
