// Generated by CoffeeScript 1.9.2
var finalhandler, fs, http, serve, serveStatic;

fs = require('fs');

http = require('http');

finalhandler = require('finalhandler');

serveStatic = require('serve-static');

serve = serveStatic('/Users/tcoats/Open/dve/examples');

http.createServer(function(req, res) {
  return serve(req, res, finalhandler(req, res));
}).listen(8080);
