// Generated by CoffeeScript 1.9.2
var WebSocket, ws;

WebSocket = require('ws');

ws = new WebSocket('ws://localhost:8081');

ws.on('open', function() {
  return console.log('open');
});

ws.on('message', function(data, flags) {
  return console.log(data);
});

ws.on('close', function() {
  return console.log('close');
});
