// Generated by CoffeeScript 1.9.2
var http, os, port, server;

os = require('os');

http = require('http');

port = 8082;

server = http.createServer(function(req, res) {
  var result;
  process.stdout.write('.');
  result = {
    server: os.hostname(),
    port: port,
    host: req.headers['host'],
    method: req.method,
    url: req.url
  };
  return res.end(JSON.stringify(result, null, 2));
});

server.listen(port, function() {
  return console.log("Home grown http server running on port " + port);
});
