// Generated by CoffeeScript 1.8.0
var DispatchNode,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __slice = [].slice;

module.exports = DispatchNode = (function() {
  function DispatchNode(url, createNode) {
    this.exec = __bind(this.exec, this);
    this._dispatchListeners = __bind(this._dispatchListeners, this);
    this._dispatchHandlers = __bind(this._dispatchHandlers, this);
    this.use = __bind(this.use, this);
    this.remove = __bind(this.remove, this);
    this.match = __bind(this.match, this);
    this._find = __bind(this._find, this);
    if (createNode == null) {
      createNode = function(url, createNode) {
        return new DispatchNode(url, createNode);
      };
    }
    this._createNode = createNode;
    this._url = url;
    this._handlers = [];
    this._listeners = [];
  }

  DispatchNode.prototype._find = function(url) {
    var listener, _i, _len, _ref;
    _ref = this._listeners;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      listener = _ref[_i];
      if (listener.url === url) {
        return listener;
      }
    }
    return null;
  };

  DispatchNode.prototype.match = function(url) {
    var listener;
    listener = this._find(url);
    if (listener == null) {
      listener = {
        url: url,
        node: this._createNode(url)
      };
      this._listeners.push(listener);
      this._listeners.sort(function(a, b) {
        return b.url.length - a.url.length;
      });
    }
    return listener.node;
  };

  DispatchNode.prototype.remove = function(url) {
    var index, listener;
    listener = this._find(url);
    if (listener != null) {
      index = this._listeners.indexOf(listener);
      this._listeners.splice(index, 1);
    }
    return this;
  };

  DispatchNode.prototype.use = function(handler) {
    var h, _i, _len;
    if (Array.isArray(handler)) {
      for (_i = 0, _len = handler.length; _i < _len; _i++) {
        h = handler[_i];
        this.use(h);
      }
    } else {
      this._handlers.push(handler);
    }
    return this;
  };

  DispatchNode.prototype._dispatch = function(items, args, next, method) {
    var exec, index;
    items = items.slice(0);
    index = 0;
    exec = function() {
      var item;
      if (index >= items.length) {
        return next.apply(null, args);
      }
      item = items[index];
      index++;
      return method(item, args, exec);
    };
    return exec();
  };

  DispatchNode.prototype._dispatchHandlers = function() {
    var args, next, url, _i;
    url = arguments[0], args = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), next = arguments[_i++];
    return this._dispatch(this._handlers, args, next, (function(_this) {
      return function(item, args, next) {
        return item.apply(null, [_this._url, url].concat(__slice.call(args), [next]));
      };
    })(this));
  };

  DispatchNode.prototype._dispatchListeners = function() {
    var args, next, url, _i;
    url = arguments[0], args = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), next = arguments[_i++];
    return this._dispatch(this._listeners, args, next, function(item, args, next) {
      var _ref;
      if (url.indexOf(item.url) !== 0) {
        return next();
      }
      return (_ref = item.node).exec.apply(_ref, [url].concat(__slice.call(args), [next]));
    });
  };

  DispatchNode.prototype.exec = function() {
    var args, next, url, _i;
    url = arguments[0], args = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), next = arguments[_i++];
    return this._dispatchHandlers.apply(this, [url].concat(__slice.call(args), [(function(_this) {
      return function() {
        return _this._dispatchListeners.apply(_this, [url].concat(__slice.call(args), [next]));
      };
    })(this)]));
  };

  return DispatchNode;

})();
